// <auto-generated />
using System;
using System.Collections.Generic;
using ValorantCoach.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ValorantCoach.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(ValorantCoachDbContext))]
    [Migration("20260918142419_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ValorantCoach.Domain.Jogadores.Jogador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<string>("Puuid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("puuid");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("regiao");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "RankAtual", "ValorantCoach.Domain.Jogadores.Jogador.RankAtual#Rank", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("RR")
                                .HasColumnType("integer")
                                .HasColumnName("rr_atual");

                            b1.Property<int>("Tier")
                                .HasColumnType("integer")
                                .HasColumnName("tier_atual");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "RiotId", "ValorantCoach.Domain.Jogadores.Jogador.RiotId#RiotId", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Nome")
                                .IsRequired()
                                .HasMaxLength(16)
                                .HasColumnType("character varying(16)")
                                .HasColumnName("nome");

                            b1.Property<string>("Tag")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasColumnName("tag");
                        });

                    b.HasKey("Id")
                        .HasName("pk_jogadores");

                    b.HasIndex("Puuid")
                        .IsUnique()
                        .HasDatabaseName("ix_jogadores_puuid");

                    b.ToTable("jogadores", (string)null);
                });

            modelBuilder.Entity("ValorantCoach.Domain.Jogadores.SnapshotRR", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CapturadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("capturado_em");

                    b.Property<Guid>("JogadorId")
                        .HasColumnType("uuid")
                        .HasColumnName("jogador_id");

                    b.Property<int>("PartidasAnalisadas")
                        .HasColumnType("integer")
                        .HasColumnName("partidas_analisadas");

                    b.Property<double>("PartidasPorDia")
                        .HasColumnType("double precision")
                        .HasColumnName("partidas_por_dia");

                    b.Property<double>("RrMedioGanho")
                        .HasColumnType("double precision")
                        .HasColumnName("rr_medio_ganho");

                    b.Property<double>("RrMedioPerdido")
                        .HasColumnType("double precision")
                        .HasColumnName("rr_medio_perdido");

                    b.Property<double>("WinRate")
                        .HasColumnType("double precision")
                        .HasColumnName("win_rate");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Rank", "ValorantCoach.Domain.Jogadores.SnapshotRR.Rank#Rank", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("RR")
                                .HasColumnType("integer")
                                .HasColumnName("rr");

                            b1.Property<int>("Tier")
                                .HasColumnType("integer")
                                .HasColumnName("tier");
                        });

                    b.HasKey("Id")
                        .HasName("pk_snapshots_rr");

                    b.HasIndex("JogadorId", "CapturadoEm")
                        .HasDatabaseName("ix_snapshots_rr_jogador_id_capturado_em");

                    b.ToTable("snapshots_rr", (string)null);
                });

            modelBuilder.Entity("ValorantCoach.Domain.Jogadores.SnapshotRR", b =>
                {
                    b.HasOne("ValorantCoach.Domain.Jogadores.Jogador", null)
                        .WithMany()
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_snapshots_rr_jogadores_jogador_id");
                });
#pragma warning restore 612, 618
        }
    }
}
